name: Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Rust code
        run: git ls-files | grep 'rs$' | xargs rustfmt --check
